export const textFields = [
   {
      name: "email",
      type: "email",
      label: "Email",
      variant: "standard",
      size: "medium",
      placeholder: "Enter your email",
      required: true,
      fullWidth: true,
   },
   {
      name: "currentPassowrd",
      type: "password",
      label: "Current password",
      variant: "standard",
      size: "medium",
      placeholder: "Enter your current password",
      required: true,
      fullWidth: true,
   },
   {
      name: "newPassword",
      type: "password",
      label: "New password",
      variant: "standard",
      size: "medium",
      placeholder: "Enter your new password",
      required: true,
      fullWidth: true,
   },
   {
      name: "confirmPassword",
      type: "password",
      label: "Confirm password",
      variant: "standard",
      size: "medium",
      placeholder: "Enter your confirm password",
      required: true,
      fullWidth: true,
   },
];
