export enum FEATURES_ADMIN {
   statistical = "statistical",
   users = "users",
   trashes = "trashes",
}
export enum TRASHES_ADMIN {
   users = "users",
}

export enum TAB_PROFILE {
   posts = "posts",
   friends = "friends",
}

export enum POSTS_ACTION {
   // Get posts
   GET_POSTS = "GET_POSTS",
   GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS",
   GET_POSTS_FAILURE = "GET_POSTS_FAILURE",
   // Create post
   CREATE_POST = "CREATE_POST",
   CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS",
   CREATE_POST_FAILURE = "CREATE_POST_FAILURE",
   // Update post
   UPDATE_POST = "UPDATE_POST",
   UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS",
   UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE",
   // Delete post
   DELETE_POST = "DELETE_POST",
   DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS",
   DELETE_POST_FAILURE = "DELETE_POST_FAILURE",
   // Like post
   LIKE_POST = "LIKE_POST",
   LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS",
   LIKE_POST_FAILURE = "LIKE_POST_FAILURE",
   // Unlike post
   UNLIKE_POST = "UNLIKE_POST",
   UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS",
   UNLIKE_POST_FAILURE = "UNLIKE_POST_FAILURE",
   // Comment post
   COMMENT_POST = "COMMENT_POST",
   COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS",
   COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE",
   // Update comment
   UPDATE_COMMENT_POST = "COMMENT_POST",
   UPDATE_COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS",
   UPDATE_COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE",
   // Delete comment
   DELETE_COMMENT_POST = "DELETE_COMMENT_POST",
   DELETE_COMMENT_POST_SUCCESS = "DELETE_COMMENT_POST_SUCCESS",
   DELETE_COMMENT_POST_FAILURE = "DELETE_COMMENT_POST_FAILURE",
}

export enum OWNER_POSTS_ACTION {
   // Get owner posts
   GET_OWNER_POSTS = "GET_OWNER_POSTS",
   GET_OWNER_POSTS_SUCCESS = "GET_OWNER_POSTS_SUCCESS",
   GET_OWNER_POSTS_FAILURE = "GET_OWNER_POSTS_FAILURE",
   // Create owner post
   CREATE_OWNER_POST = "CREATE_OWNER_POST",
   CREATE_OWNER_POST_SUCCESS = "CREATE_OWNER_POST_SUCCESS",
   CREATE_OWNER_POST_FAILURE = "CREATE_OWNER_POST_FAILURE",
   // Update owner post
   UPDATE_OWNER_POST = "UPDATE_OWNER_POST",
   UPDATE_OWNER_POST_SUCCESS = "UPDATE_OWNER_POST_SUCCESS",
   UPDATE_OWNER_POST_FAILURE = "UPDATE_OWNER_POST_FAILURE",
   // Delete owner post
   DELETE_OWNER_POST = "DELETE_OWNER_POST",
   DELETE_OWNER_POST_SUCCESS = "DELETE_OWNER_POST_SUCCESS",
   DELETE_OWNER_POST_FAILURE = "DELETE_OWNER_POST_FAILURE",
   // Like owner post
   LIKE_OWNER_POST = "LIKE_OWNER_POST",
   LIKE_OWNER_POST_SUCCESS = "LIKE_OWNER_POST_SUCCESS",
   LIKE_OWNER_POST_FAILURE = "LIKE_OWNER_POST_FAILURE",
   // Unlike owner post
   UNLIKE_OWNER_POST = "UNLIKE_OWNER_POST",
   UNLIKE_OWNER_POST_SUCCESS = "UNLIKE_OWNER_POST_SUCCESS",
   UNLIKE_OWNER_POST_FAILURE = "UNLIKE_OWNER_POST_FAILURE",
   // Comment owner post
   COMMENT_POST = "COMMENT_POST",
   COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS",
   COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE",
   // Update owner comment
   UPDATE_COMMENT_POST = "COMMENT_POST",
   UPDATE_COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS",
   UPDATE_COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE",
   // Delete owner comment
   DELETE_COMMENT_POST = "DELETE_COMMENT_POST",
   DELETE_COMMENT_POST_SUCCESS = "DELETE_COMMENT_POST_SUCCESS",
   DELETE_COMMENT_POST_FAILURE = "DELETE_COMMENT_POST_FAILURE",
}
