export const signInState$ = (state) => state.signIn;
export const signUpState$ = (state) => state.signUp;
export const signOutState$ = (state) => state.signOut;
export const profileState$ = (state) => state.profile;
export const postsState$ = (state) => state.posts;
export const trashPostsState$ = (state) => state.trashPosts;
export const ownerPostsState$ = (state) => state.ownerPosts;
export const postState$ = (state) => state.post;
export const usersState$ = (state) => state.users;
